### ISSUE TITLE
Failing "Update kotlin" builds/actions for kotlin 2.0.0

### ISSUE THREAD

**Issue by jsytal1** [android/architecture-templates#158]
These actions failed after updating kotlin to 2.0.0:

https://github.com/android/architecture-templates/actions/runs/9899323193
https://github.com/android/architecture-templates/actions/runs/9899323188
https://github.com/android/architecture-templates/actions/runs/9899311922
https://github.com/android/architecture-templates/actions/runs/9899311918

relevant logs:
https://github.com/android/architecture-templates/actions/runs/9899323193/job/27347996856#step:5:185

``
e: This version (1.5.14) of the Compose Compiler requires Kotlin version 1.9.24 but you appear to be using Kotlin version 2.0.0 which is not known to be compatible.  Please consult the Compose-Kotlin compatibility map located at https://developer.android.com/jetpack/androidx/releases/compose-kotlin to choose a compatible version pair (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).
``

https://github.com/android/architecture-templates/actions/runs/9899323193/job/27347996856#step:5:211

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core-ui:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org./

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':core-ui:compileDebugKotlin'.
```

**Comment by jsytal1** [comment]
From: https://developer.android.com/jetpack/androidx/releases/compose-kotlin

> 
> Compose Compiler Version | Compatible Kotlin Version
> -- | --
> Use the [Compose Compiler Gradle plugin](https://developer.android.com/develop/ui/compose/compiler) to enable Compose. | 2.0.0+

So the `Compose Compiler` should be replaced with the `Compose Compiler Gradle plugin`

**Comment by JoseAlcerreca** [comment]
Thanks @jsytal1!
